server:
  port: 9000
  servlet:
    context-path: /

spring:
  application:
    name: mall-cloud-gateway
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
        namespace: 90f44db4-bf87-4630-8864-c3b1cb98e2fd
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
    gateway:
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求 allowedOrigins: “*” 允许所有网站
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
              - "http://localhost:4000"
              - "http://127.0.0.1:4000"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      retries: 3
    consumer:
      auto-offset-reset: latest
  zipkin:
    sender:
      type: kafka # 默认是 web
    base-url: http://127.0.0.1:9411/
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: Asia/Shanghai


nacos:
  gateway:
    route:
      config:
        data-id: mall-cloud-gateway-router
        group: mall-cloud

management:
  endpoints:
    web:
      exposure:
        include: '*'  # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 *, 可以开放所有端点
  endpoint:
    health:
      show-details: always